name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  release:
    types: [ published ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Test package creation
      run: npm pack --dry-run

  code-quality:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run TypeScript compiler check
      run: npx tsc --noEmit

    - name: Run linting (non-blocking)
      run: npm run lint
      continue-on-error: true

    - name: Check code formatting (non-blocking)
      run: npm run format:check
      continue-on-error: true

    - name: Check bundle size (non-blocking)
      run: npm run build && npm run size-check
      continue-on-error: true

  security:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run security audit (non-blocking)
      run: npm audit --audit-level=moderate
      continue-on-error: true

    - name: Check for known vulnerabilities (non-blocking)
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: '--severity-threshold=high'
      continue-on-error: true

  documentation:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check documentation links (non-blocking)
      uses: lycheeverse/lychee-action@v1.5.0
      with:
        args: '--max-redirects 3 --timeout 30 --exclude mailto: --exclude tel: --exclude file: --exclude localhost --exclude 127.0.0.1'
      continue-on-error: true

    - name: Check markdown formatting (non-blocking)
      uses: DavidAnson/markdownlint-cli2-action@v12
      with:
        globs: "**/*.md"
      continue-on-error: true

  deploy:
    runs-on: ubuntu-latest
    needs: [test, security]
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Publish to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
